# Generated by Django 5.1.4 on 2024-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('prep_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
